### ISSUE TITLE
SDK and Coder MiP

### ISSUE THREAD

**Issue by seliger** [WowWeeLabs/MiP-Node.js-SDK#2]
I pulled down the SDK this evening and was having difficulty getting it to work with our new Coder MiP. I would attempt to run the example and it would "hang." Running in debug mode, I could clearly seeing the CoderMiP advertising itself when noble would scan. 

I added some debug lines and determined that PRODUCT_ID for Coder MiP is really 55, rather than 5. I don't know the significance of 5 vs 55 (MiP vs Coder MiP?). I was able to work around the issue by setting the value in constants.json to 55, but that doesn't seem like a scalable option in the event you might have MiPs and Coder MiPs together concurrently.

Beyond the workaround, I haven't dug into a larger solution, but at least wanted to bring this to your attention.

**Comment by gyancse08** [comment]
I am getting this error while running example.js. Any idea?
    throw new Error('No compatible USB Bluetooth 4.0 device found!');
    ^

Error: No compatible USB Bluetooth 4.0 device found!
    at BluetoothHciSocket.bindUser (C:\Users\gyprakas\node_modules\bluetooth-hci-socket\lib\usb.js:70:11)
    at BluetoothHciSocket.bindRaw (C:\Users\gyprakas\node_modules\bluetooth-hci-socket\lib\usb.js:28:8)
    at Hci.init (C:\Users\gyprakas\node_modules\noble\lib\hci-socket\hci.js:101:35)

**Comment by atodkar** [comment]
I see its been long time since the question asked but for those who are facing same issue, the reasone for "No compatible USB Bluetooth 4.0 device found!" is the requirement to install WinUSB driver. You can follow URL - https://zadig.akeo.ie to install those drivers and then make sure to use ONLY MiP with this SDK. Additional information is also available on https://github.com/noble/node-bluetooth-hci-socket. Bluetooth HCI Socket library is used internally by Wowweemip.

This SDK doesnot work with MinionMiP due to PRODUCT_ID difference. Unfortunately, there is no comprehensive documentation on all such requirements and FAQ.
